/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/restaurants/{restaurantId}/sync/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload a batch of events; idempotent by eventId, one result per event */
    post: operations["upload"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/restaurants/{restaurantId}/devices/{deviceId}/deactivate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Unlink a device for good; its token and PIN logins stop working */
    post: operations["deactivate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/restaurants/{restaurantId}/devices/pairings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a one-time pairing code (QR) to link a new device */
    post: operations["createPairing"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/devices/pair": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Redeem a pairing code from the new device; returns its token once */
    post: operations["pair"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Exchange a refresh token for a new token pair */
    post: operations["refresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/pin-login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Log in with a PIN from a registered device (shift session, no refresh) */
    post: operations["pinLogin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke a refresh token */
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Log in with email and password */
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/device-login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Session of a linked device itself, for synchronisation (no user) */
    post: operations["deviceLogin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/change-pin": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Change the PIN, proving identity with the current PIN or password */
    post: operations["changePin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/change-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Change the password; closes every other session */
    post: operations["changePassword"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/restaurants/{restaurantId}/sync/snapshot": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Master data a device needs to work offline */
    get: operations["snapshot"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/restaurants/{restaurantId}/devices": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Devices of the restaurant, active and unlinked */
    get: operations["list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/permissions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Catalog of permissions */
    get: operations["list_1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Current user, restaurants and permissions */
    get: operations["me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    EventDto: {
      /** Format: uuid */
      eventId: string;
      type: string;
      /** Format: uuid */
      aggregateId: string;
      /** Format: int64 */
      restaurantId: number;
      /** Format: uuid */
      deviceId: string;
      /** Format: int64 */
      userId?: number;
      /** Format: int32 */
      schemaVersion: number;
      payload: components["schemas"]["JsonNode"];
      hlc: string;
      /** Format: int64 */
      epoch: number;
      /** Format: int64 */
      seq?: number;
      /** Format: date-time */
      createdAt: string;
    };
    JsonNode: unknown;
    UploadEventsRequest: {
      events: components["schemas"]["EventDto"][];
    };
    EventResultDto: {
      /** Format: uuid */
      eventId?: string;
      /** @enum {string} */
      status?: "APPLIED" | "DUPLICATE" | "REJECTED";
    };
    UploadEventsResponse: {
      results?: components["schemas"]["EventResultDto"][];
    };
    DeviceResponse: {
      /** Format: int64 */
      id?: number;
      /** Format: uuid */
      uuid?: string;
      code?: string;
      name?: string;
      /** @enum {string} */
      type?: "POS" | "KDS" | "ADMIN";
      active?: boolean;
      /** Format: date-time */
      lastSeenAt?: string;
    };
    CreatePairingRequest: {
      deviceName: string;
      /** @enum {string} */
      deviceType: "POS" | "KDS" | "ADMIN";
    };
    PairingResponse: {
      code?: string;
      /** Format: date-time */
      expiresAt?: string;
    };
    PairRequest: {
      code: string;
    };
    PairResponse: {
      /** Format: int64 */
      deviceId?: number;
      /** Format: uuid */
      deviceUuid?: string;
      deviceCode?: string;
      name?: string;
      /** @enum {string} */
      type?: "POS" | "KDS" | "ADMIN";
      /** Format: int64 */
      restaurantId?: number;
      deviceToken?: string;
    };
    RefreshRequest: {
      refreshToken: string;
    };
    TokenResponse: {
      accessToken?: string;
      refreshToken?: string;
      /** Format: int64 */
      expiresIn?: number;
    };
    PinLoginRequest: {
      /** Format: int64 */
      deviceId: number;
      deviceToken: string;
      pin: string;
    };
    LoginRequest: {
      email: string;
      password: string;
    };
    DeviceLoginRequest: {
      /** Format: int64 */
      deviceId: number;
      deviceToken: string;
    };
    ChangePinRequest: {
      currentSecret: string;
      newPin: string;
    };
    ChangePasswordRequest: {
      currentPassword: string;
      newPassword: string;
    };
    PosUserDto: {
      /** Format: int64 */
      id?: number;
      displayName?: string;
      pinHash?: string;
      roles?: string[];
      permissions?: string[];
    };
    SnapshotResponse: {
      /** Format: date-time */
      generatedAt?: string;
      users?: components["schemas"]["PosUserDto"][];
    };
    MeResponse: {
      /** Format: int64 */
      id?: number;
      email?: string;
      displayName?: string;
      restaurantIds?: number[];
      roles?: string[];
      permissions?: string[];
      /** Format: int64 */
      deviceId?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  upload: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        restaurantId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UploadEventsRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["UploadEventsResponse"];
        };
      };
    };
  };
  deactivate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        restaurantId: number;
        deviceId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["DeviceResponse"];
        };
      };
    };
  };
  createPairing: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        restaurantId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePairingRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PairingResponse"];
        };
      };
    };
  };
  pair: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PairRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PairResponse"];
        };
      };
    };
  };
  refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["TokenResponse"];
        };
      };
    };
  };
  pinLogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PinLoginRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["TokenResponse"];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["TokenResponse"];
        };
      };
    };
  };
  deviceLogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeviceLoginRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["TokenResponse"];
        };
      };
    };
  };
  changePin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePinRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  snapshot: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        restaurantId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["SnapshotResponse"];
        };
      };
    };
  };
  list: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        restaurantId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["DeviceResponse"][];
        };
      };
    };
  };
  list_1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": string[];
        };
      };
    };
  };
  me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["MeResponse"];
        };
      };
    };
  };
}
